

POST http://localhost:4000
Content-Type: application/json

{
  "date":"09.09.2qqwewe123123024",
  "instruments":"tqqweweqwe123eqweqwesqwe11232312123233123qwe334t",
  "typeError":"te123st4",
  "description":"Teqsqwet description",
  "client":"rocktieqwentin21"
}

###

PUT http://localhost:4000/changeOrderByParams/1
Content-Type: application/json

{
  "master":"123",
  "status": "готов"
}
###

GET http://localhost:4000/getOrderByParams/1
###

GET http://localhost:4000/getStatusOfCount